<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.1</TargetFramework>
        <RootNamespace>DotnetRefScan</RootNamespace>
        <Nullable>enable</Nullable>
        <Product>DotnetRefScan</Product>
        <Authors>Simon Polan</Authors>
        <Copyright>Copyright © Simon Polan 2026</Copyright>
        <Version>3.1.2</Version>
        <Description>Reference scanner for Dotnet applications. It loads NuGets and Libman references from your source code.</Description>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <PackageProjectUrl>https://github.com/simonpolan/DotnetRefScan</PackageProjectUrl>
        <RepositoryUrl>https://github.com/simonpolan/DotnetRefScan</RepositoryUrl>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
        <PackageReleaseNotes>Improved stability, error handling and extensibility of CSharpProjectFileUsedReferencesProvider.</PackageReleaseNotes>
        <PackageReadmeFile>README.md</PackageReadmeFile>
    </PropertyGroup>

    <PropertyGroup>
        <DocumentationFile>DotnetRefScan.xml</DocumentationFile>
    </PropertyGroup>

    <ItemGroup>
        <None Include="..\README.md" Pack="true" PackagePath="\" />
        <None Include="..\LICENSE.txt" Pack="true" PackagePath="\" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="System.Text.Json" Version="8.0.6" />
    </ItemGroup>

    <ItemGroup>
        <!-- Support for mocking e.g. NSubstitute. -->
        <InternalsVisibleTo Include="DynamicProxyGenAssembly2" />
        <InternalsVisibleTo Include="$(MSBuildProjectName).Tests" />
    </ItemGroup>

</Project>
