<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.1</TargetFramework>
        <RootNamespace>DotnetRefScan</RootNamespace>
        <Nullable>enable</Nullable>
        <Product>DotnetRefScan</Product>
        <Authors>Simon Polan</Authors>
        <Copyright>Copyright © Simon Polan 2026</Copyright>
        <Version>2.3.0</Version>
        <Description>Reference scanner for Dotnet applications. It loads NuGets and Libman references from your source code.</Description>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <PackageProjectUrl>https://github.com/simonpolan/DotnetRefScan</PackageProjectUrl>
        <PackageLicenseFile>LICENSE</PackageLicenseFile>
        <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
        <PackageReleaseNotes>Reads license information for NuGet packages from NuGet API (copyright, license type, project url).</PackageReleaseNotes>
        <PackageReadmeFile>README.md</PackageReadmeFile>
    </PropertyGroup>

    <PropertyGroup>
        <DocumentationFile>DotnetRefScan.xml</DocumentationFile>
    </PropertyGroup>

    <ItemGroup>
        <None Include="..\README.md" Pack="true" PackagePath="\" />
        <None Include="..\LICENSE" Pack="true" PackagePath="\" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="System.Text.Json" Version="10.0.1" />
    </ItemGroup>

    <ItemGroup>
        <!-- Support for mocking e.g. NSubstitute. -->
        <InternalsVisibleTo Include="DynamicProxyGenAssembly2" />
        <InternalsVisibleTo Include="$(MSBuildProjectName).Tests" />
    </ItemGroup>

</Project>
