<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.1</TargetFramework>
        <RootNamespace>DotnetRefScan</RootNamespace>
        <Nullable>enable</Nullable>
        <Product>DotnetRefScan</Product>
        <Authors>Simon Polan</Authors>
        <Copyright>Copyright © Simon Polan 2025</Copyright>
        <Version>2.3.0</Version>
        <Description>Reference scanner for Dotnet applications. It loads NuGets and Libman references from your source code.</Description>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <PackageProjectUrl>https://github.com/simonpolan/DotnetRefScan</PackageProjectUrl>
        <PackageLicenseFile>LICENSE</PackageLicenseFile>
        <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
        <PackageReleaseNotes>Package references versions could be auto-updated in the license file + the license file table can be auto-formatted.</PackageReleaseNotes>
        <PackageReadmeFile>README.md</PackageReadmeFile>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
        <DocumentationFile>DotnetRefScan.xml</DocumentationFile>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
        <DocumentationFile>DotnetRefScan.xml</DocumentationFile>
    </PropertyGroup>

    <ItemGroup>
        <None Include="..\README.md" Pack="true" PackagePath="\" />
        <None Include="..\LICENSE" Pack="true" PackagePath="\" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
        <PackageReference Include="CliWrap" Version="3.10.0" />
    </ItemGroup>

    <ItemGroup>
        <!-- Support for mocking e.g. NSubstitute. -->
        <InternalsVisibleTo Include="DynamicProxyGenAssembly2" />
        <InternalsVisibleTo Include="$(MSBuildProjectName).Tests" />
    </ItemGroup>

</Project>
